### ISSUE TITLE
Bring back like gesture

### ISSUE THREAD

**Issue by SuperSandro2000** [Mosc/Glider#103]
Before the rewrite you could like posts by sipping to the right. With the rewrite this is no longer possible.

**Comment by naiyerasif** [comment]
From a usability perspective, swipes are in direct conflict with Android's back gesture. I've had many accidental upvotes due to this and am glad that the gesture is gone.

**Comment by Mosc** [comment]
Yeah, swipe gestures are tricky; lacking in discoverability, and conflicting with mobile operating systems moving more towards swipe-based navigation. Although I know some people liked them, they're not coming back as long as I can think of alternatives. That alternative in this case is the "Action buttons" on the settings page. Please try that one out!

**Comment by SuperSandro2000** [comment]
I just installed 1.18.1 again and I was granted with this message in the introduction:

![Screenshot_20231109_161651](https://github.com/Mosc/Glider/assets/7258858/bd4726d9-dc15-431f-86c3-9683c24b41a3)

**Comment by Mosc** [comment]
I'm aware. I made that! If you prefer v1.18.1 you're free to continue using that version.
