### ISSUE TITLE
Threads opened via URL do not change if another link is clicked

### ISSUE THREAD

**Issue by GOATS2K** [Mosc/Glider#105]
Hi, congrats with V2 - I've been a happy Glider user for a long time. :)

If an external HN link is clicked, the page loads as expected in the app, however - if another link is clicked, the app doesn't do anything.

Please see the attached video. 
My inputs aren't showing, but I keep trying to select different links.

https://github.com/Mosc/Glider/assets/55696338/0fbc9a24-c92e-4806-8cee-f545e69f82bc

**Comment by Mosc** [comment]
Could you share the name of the app that you're launching the links from? I've tried to replicate this in several apps, but it's behaving correctly on my end.

**Comment by GOATS2K** [comment]
This was in Pushbullet.

**Comment by Mosc** [comment]
Interestingly not every app exhibits this behavior (the Intents they send can differ slightly), and in Android 14 I can only replicate it in Pushbullet by switching apps, not by using the back gesture. Nonetheless, this has now been fixed (970b3adc74010cfb1fc0885e30833f0f9a0cb02d) and will be part of the next release.
