### ISSUE TITLE
Themed icon incorrect

### ISSUE THREAD

**Issue by ldavison** [Mosc/Glider#108]
After upgrading from 1.18.1 to 2.0.0 or 2.1.0 the themed icon is just a blank circle:

![Screenshot_20231028-142814.png](https://github.com/Mosc/Glider/assets/479539/4b9ec95b-20c0-41d2-b71f-a43d78317b62)

It looked fine on 1.18.1:

![Screenshot_20231028-143314.png](https://github.com/Mosc/Glider/assets/479539/2a6dd831-a208-4911-b785-5fa3bc8d35e8)

**Comment by Mosc** [comment]
Yup, reported in #101 before. Fixed in ff4040c2a20384a69ffe5c6d2da5a7efb3296409 but not released yet.
