### ISSUE TITLE
Comments lag and scrolling flash

### ISSUE THREAD

**Issue by LECAGO** [Mosc/Glider#109]
1) Large posts with many (1000+) comments like those in the "Catch up" tab cause major lag when first opened. I have to wait above 5 seconds as the comments load in one by one. The loading bar above the post title "finishes loading" way before all the comments are fully loaded, so from a UX standpoint I have no indication on how long I have to wait in order to not get hit with lag.

2) When scrolling the comments sometimes I hold my initial tap too long and this causes the selected comment to flash as if it were long tapped. It's not really a bug but I'm on dark mode with pure black so it is quite jarring to have a flash every time I scroll.

**Comment by Mosc** [comment]
There's definitely some lag on opening large discussions. It's kind of a natural consequence of the way the Hacker News API is designed, where every item has to be retrieved individually, making 1000+ comments result in 1000+ network calls. There may be options for optimization which I'll continue to look into. The UX indicating that loading is finished when it isn't sounds like something that also needs to be looked into.

As for the comment highlighting, I don't think I can really do anything about that. We do want the items to give feedback when long-pressed.

**Comment by Mosc** [comment]
I've made some optimizations in v2.4.0 that should improve the loading performance. Could you report whether or not you still consider this an issue?

**Comment by LECAGO** [comment]
There's a massive improvement, great work. Marking as closed.
