### ISSUE TITLE
Glider 2.0 does not support use of in-app browser

### ISSUE THREAD

**Issue by DeepakParamkusam** [Mosc/Glider#113]
Glider v1.8.1 had the "Open links in custom tabs" option which opened links in in-app browser. This setting appears to be missing in v2.0. Is this intended? If yes, do you plan to add this option?

Thanks for the great app!

**Comment by Mosc** [comment]
There's a good chance this setting will return. It requires some custom code that I had hoped to not have to write, but that's certainly not insurmountable.

**Comment by Mosc** [comment]
A setting for this has been added (3ab5c792c9797ca22454789388f87d47469a3394, a5208a008729e282f3af022e83f4f2916dda2b0c) and will be part of the next release.
