### ISSUE TITLE
Feature Request: Disable scrolling stretch-and-squish (V2)

### ISSUE THREAD

**Issue by AutumnalAntlers** [Mosc/Glider#118]
I'm running V2.0.0 Android 9 on a Samsung S8, and the first thing I did after updating was look for an in-app option to disable the stretchy scrolling animation. The second thing I did was to toggle "System Settings -> Accessability -> Visability enhancements -> Disable Animations", but that didn't do it. The third thing I did was to unlock the developer settings and set all of "Window animation scale", "Transition animation scale", and "Animator duration scale" to "Off" (not my first rodeo :p). This also had no effect, so I figure these four settings must only apply to "system" activities or components vs whatever stack is in-use? Not my area of expertise.

Aside from this and gestures (which I belive I saw an existing issue for, will check out action buttons when they hit fdroid), the app still looks great! Congrats c:

**Comment by Mosc** [comment]
One of the downsides of using Flutter as the development framework for this app is that it doesn't respect system settings as much as native apps. To solve the overscroll effect not matching the expected animation on older Android versions I've overridden the default overscroll indicator to the glowing indicator for Android versions below 12 in 10ddeee4c0ae716f8257419949bfd3a07cc9662a. Will be part of the next release.
