### ISSUE TITLE
FormatException in the inbox tab

### ISSUE THREAD

**Issue by Bilal-io** [Mosc/Glider#120]
There is an error in the inbox tab stating "Something went wrong FormatException" the Retry button doesn't fix the issue.

**Comment by Mosc** [comment]
Is it perhaps possible that you were seeing this behavior on version 2.0.0, rather than the latest 2.1.0? It took some time for the F-Droid build to update, so I would not be surprised. I'm assuming this was fixed with #93, but let me know if you're still having issues on 2.1.0.
