### ISSUE TITLE
System buttons bar have white buttons on white background on older androids (glider 2.x)

### ISSUE THREAD

**Issue by Porkepix** [Mosc/Glider#123]
System buttons bar are white over white background on older Android versions, making it very hard to read.

See this screenshot:
<details>
<summary>
Screenshot
</summary>

![Screenshot_20231028-225602](https://github.com/Mosc/Glider/assets/709500/cd562258-b525-4b4d-ab49-419219e2eddb)
</details>

And for reference those similar issues:
https://github.com/Livinglist/Hacki/issues/184
https://github.com/beemdevelopment/Aegis/issues/531
https://github.com/celzero/rethink-app/issues/802

**Comment by Mosc** [comment]
Fixed in 77e10378687630b5a0be4258dbec32453d07aa3f.
