### ISSUE TITLE
Page scroll buttons obscure comments at bottom of page

### ISSUE THREAD

**Issue by aelnona** [Mosc/Glider#127]
![Screenshot_20231103-215038.png](https://github.com/Mosc/Glider/assets/103208374/a72f3305-7b6b-49a5-9b50-796e8c4e46cb)

The buttons on the right of the screen block some of the text in the bottom comments. This is fine for most comments, but one cannot scroll the view such that the final comments become above the buttons.

**Comment by Mosc** [comment]
Thanks, fixed in ee99ecb1fa31302155704a349f67dc3ee387c247.
