### ISSUE TITLE
Overlay buttons are often at a bad spot

### ISSUE THREAD

**Issue by sjaeckel** [Mosc/Glider#128]
1. When writing a reply the `reply` button hovers over the text field and one can't read the end of the last line.

2. The submit button is too prominent on the main view. It's not that important to submit a new story IMO, since this is mostly a viewer. This should be a menu point instead if you'd ask me.

The same applies to the thread navigation buttons, but they can be disabled so I'm fine.

Overall good rewrite! Took a bit time to get used to the new design but it's nice :-)

**Comment by Mosc** [comment]
Your first remark is related to #127, and it's a good point: several pages with floating action buttons deserve more padding at the bottom so we can at least see all of the content.

I can see the point about the submit button. I debated its inclusion for a while. In the end the increased discoverability won out, but it's not a given that it'll stay that way forever.

**Comment by Mosc** [comment]
The first point is fixed in ee99ecb1fa31302155704a349f67dc3ee387c247. As mentioned, I'm not changing the floating action button for now.
