### ISSUE TITLE
Edit function

### ISSUE THREAD

**Issue by amalic** [Mosc/Glider#13]
Since I communicate regularly in three languages, I have auto-correct turned off on my phone. This results in  typos, which I have to fix through the web browser. It would be great if this was possible through the app.

**Comment by Mosc** [comment]
Sounds good. As far as I know that would be a unique feature among Hacker News apps. :)

As with other interactive actions, such as upvoting and replying, the official API does not provide support for this. We'd have to send a POST request to the website at the `/xedit` endpoint with our credentials, an ID and the updated text. One complicating factor is that posts are only editable for an undocumented period of around two hours. The app has no way of knowing for certain whether something is still editable, and I'm not even sure the server will respond with a sane error code if we submit an edit after this moment has passed. I guess we'd have to show some kind of warning that edits may fail for this reason.

Open questions:
- [ ] What's the server response on an invalid `/xedit` call?
- [ ] Can we only edit comments, or submissions as well? How do we handle URL submissions, or, dare I say it, polls even?

**Comment by Mosc** [comment]
This has been implemented as part of 00d9adb8d36b056a535c67ba32cdda48a6c4504c and should be available in the next release.
