### ISSUE TITLE
Feature: Read Style

### ISSUE THREAD

**Issue by xhzhe** [Mosc/Glider#132]
I'm using the old version which i change the transparency of read items. I am so glad to see the new style of it, but it make me hard to recgonize which item i have read or not.

Could you help make it easier (an option? maybe) to discriminate read items?

**Comment by Mosc** [comment]
The app currently displays read stories with 75% opacity, whereas before the redesign they were displayed at 66.7% opacity. That might make a noticeable difference for you. I'll do some experimentation on this.

**Comment by xhzhe** [comment]
Thanks, I'm using 25% now and it looks great in my phone.

![MicrosoftTeams-image](https://github.com/Mosc/Glider/assets/24984102/71292d67-3f84-44f2-b29e-5031d23b5253)

**Comment by Mosc** [comment]
Oh, I consider that way too extreme. That's barely readable! I made visited items slightly more faded in be53f1091a8c98f292709a0eb086e7141dccb6a4 (back to the older 66.7%), but that's about the max I want to support. And I'm afraid this is too niche for me to make a setting for. I'd like to keep the amount of settings relatively small. Sorry!

**Comment by xhzhe** [comment]
Yeah, you are right, I just don't want to reread the items which i have read, which I still not figure out a good practice for it.
