### ISSUE TITLE
Link from external app only opens an empty gray screen

### ISSUE THREAD

**Issue by zxjinn** [Mosc/Glider#139]
First of all, I've been a Glider user for many moons and I sincerely appreciate the ongoing effort that goes into making this app so good.

My issue arose not after the 2.0 release, but after the most recent update that I got on the 5th of November.

When I click on a link from Feedly (and other apps) that go to news.ycombinator.com all I get is a gray screen from Glider. See attached gif for what happens in Feedly.

Interestingly enough, when I am in Firefox and I click the "Open in app" menu option, it works fine, but all other apps I've tested give me the gray empty screen.

Some more details:
OS: Android 14
Phone: Pixel 5
Glider version: 2.2.0
![screenrecord](https://github.com/Mosc/Glider/assets/1184723/35a3107a-099b-46ab-88d1-c7c21ebb4f26)

**Comment by Mosc** [comment]
Thanks, but already reported in #135. Fixed on the master branch, will be part of the next release!

**Comment by zxjinn** [comment]
My mistake! I looked for an existing issue before I opened this and didn't see anything, but I mistakenly only reviewed the open issues.
Thank you!
