### ISSUE TITLE
Low scrolling framerate

### ISSUE THREAD

**Issue by kaibagley** [Mosc/Glider#144]
Hey, 

I'm sure you may have noticed but the framerate seems much lower than that of my phone's (120hz).

I don't think this was the case on glider <2.0 but I can't really remember..

Thanks!

**Comment by Mosc** [comment]
Performance is indeed lacking and something I've been meaning to dive into. I've made some improvements that have not been released to production yet. If you'd like, you could test them on the build attached to this workflow: https://github.com/Mosc/Glider/actions/runs/6942982921. That likely would clear your current settings and login status though, as it is not signed with production keys.

**Comment by kaibagley** [comment]
Testing it out now, it does seem much smoother! Let me know if you'd like me to test out anything else

**Comment by Mosc** [comment]
Good to hear. This is being released as part of v2.4.0 and I'll consider this solved. There may be more performance issues lurking, feel free to open an issue if you encounter anything specific.
