### ISSUE TITLE
Opening an HN link from the app clears navigation stack

### ISSUE THREAD

**Issue by mihe** [Mosc/Glider#149]
This has been happening for a while, so isn't something new to 2.5.0, although I'm fairly sure this wasn't a problem pre-2.0, but whenever you tap an HN link from within the app itself it seems to clear the navigation stack (or however Flutter represents this) and when pressing the back button (or perform the equivalent gesture I guess) you end up exiting the app completely.

Even a link that points to the same HN discussion seems to have this effect (despite it not navigating anywhere) like what you usually find in big threads where dang pins links to all the separate pages, as seen [here](https://news.ycombinator.com/item?id=38309611).

I'm using a OnePlus 8T running Android 13, if that matters.

**Comment by mihe** [comment]
Oh, and I guess it's relevant to mention that I have Glider set to be the default app for HN links through the "Open Supported Links" toggle in the app info page.

**Comment by Mosc** [comment]
The aforementioned workaround has been added in 7d784748d38de0e8aa6003561d371749e075134f. Not an ideal fix, but good enough to resolve your issue.
