### ISSUE TITLE
Navigation: Swipe to the right to go back

### ISSUE THREAD

**Issue by onedr0p** [Mosc/Glider#16]
It would be neat to swipe right to go back to previous views

See this gif

![ezgif com-gif-maker](https://user-images.githubusercontent.com/213795/119016746-4af15780-b968-11eb-8f21-8a8ed7c57838.gif)

Thanks!

**Comment by Mosc** [comment]
I've considered it. One reason I haven't implemented it so far is that I think it will conflict with the swipe option for comments. The other one is that, if this is the type of navigation one prefers, why not simply use the OS's gesture navigation instead?

**Comment by onedr0p** [comment]
A lot of apps I use support this type of navigation, so it's a bit odd for me using Glider.

You would probably need a settings view with options to enable or disable this type of navigation and an alternative way to react to comments. I understand this is a big ask but would love to see it. This is the only well supported Hacker News android app, and it's great so far!

**Comment by Mosc** [comment]
I had a go at this and wasn't too happy with the result. The typical suggestion for implementing swipe-to-go-back in Flutter is to just use [CupertinoPageRoute](https://api.flutter.dev/flutter/cupertino/CupertinoPageRoute-class.html) which has this functionality baked in. That results in a very iOS-y interaction that doesn't look natural on Android devices. Given this, I tried to customize and slim down the CupertinoPageRoute to fit my requirements, but that still leaves several hundred lines of code that I don't fully grasp and am not excited to commit to this repository.

If someone has a better suggestion for an implementation, such as a well-documented Flutter package that provides this feature, I'd like to hear about it.

**Comment by onedr0p** [comment]
Thanks for the update, I wish I could provide some info on that but I am clueless about Flutter.

**Comment by Mosc** [comment]
Implemented in dabb2684abf7484b89a743434546538ddc85d6a6 and released to production as part of v1.9.0. In the end I did choose the option of copying and modifying the `CupertinoPageRoute`, throwing out any code I didn't need and customizing the behavior to fade the underlying page rather than sliding it into view. To prevent any conflict with the existing sliding actions, the swipe gesture only triggers on the edge of the page.

**Comment by shambu2k** [comment]
U

**Comment by shambu2k** [comment]
I use pixel like navigation where you navigate back by swiping from the edge of the screen.
So sometimes, swiping from the left when in news page, it goes back to the feed and also closes the app. (Screen recording below)
I would like to propose an option to enable the user to disable or enable the gesture navigation feature within the app.

**Comment by Mosc** [comment]
Hmm. That's probably the same underlying problem as #32, actually. I think this is a bug in the Flutter framework as https://github.com/flutter/flutter/issues/83087 describes the same behavior. Would you mind opening a separate issue for this to make it easier to keep track of?

**Comment by shambu2k** [comment]
> Hmm. That's probably the same underlying problem as #32, actually. I think this is a bug in the Flutter framework as [flutter/flutter#83087](https://github.com/flutter/flutter/issues/83087) describes the same behavior. Would you mind opening a separate issue for this to make it easier to keep track of?

sure
