### ISSUE TITLE
Search screen's background doesn't respect the Pure Black theme preference

### ISSUE THREAD

**Issue by naiyerasif** [Mosc/Glider#160]
Here are screenshots to showcase this behaviour.

This is how my frontpage looks with Pure Black theme.
![Screenshot_20231212-212338](https://github.com/Mosc/Glider/assets/19614213/d793f8f2-4944-4782-a117-71344ff4eca7)

And this is how the Search screen looks with the same settings.
![Screenshot_20231212-212358](https://github.com/Mosc/Glider/assets/19614213/3f646034-400a-4cc0-ba34-7fc287729006)

---
Observed on Glider 2.6.0 on Android 14

**Comment by Mosc** [comment]
Agreed, the search view is too bright (in dark mode) for the pure background setting. In 3aec11d06c36797106d4d4fc37f3b01a9f750f1b I've made it significantly darker, though not perfectly dark because the search view will have a slight elevation.
