### ISSUE TITLE
"Story favicons" setting not preserved across restarts

### ISSUE THREAD

**Issue by khimaros** [Mosc/Glider#169]
in settings, toggle the "Story favicons" setting. observe the it displays correctly after toggle.

swipe to close Glider from the window overlay and then launch again. note setting has been toggled back on.

**Comment by Mosc** [comment]
I'm afraid I can't reproduce this behavior. Do other settings persist properly? And what app version have you experienced this issue on?

**Comment by khimaros** [comment]
version is F-Droid 2.8.0. clearing application storage and starting over, i no longer have this issue. maybe there was a migration issue from an earlier version?

**Comment by khimaros** [comment]
closing this issue, as i am no longer affected.
