### ISSUE TITLE
About localization

### ISSUE THREAD

**Issue by ddarfantasy** [Mosc/Glider#17]
I want the project in my native language at first, but after thinking carefully, I think it's not necessary to localize the project since Hacker News is in English. And incomplete translation would make the app looking weird.
Do you think it's worthwhile to make translations available? If so, I'm glad to help translate it into Simplified Chinese.

**Comment by Mosc** [comment]
Yes, this is something I'd like to add at some point. The app is written using Flutter, which supports internationalization using the ARB format, which is basically just a specific implementation of JSON. I think it'd be nice for the community to provide translations for languages that I do not speak. However, strings are currently just hardcoded throughout the code, so adjustments would be needed to support this functionality.

**Comment by Mosc** [comment]
Localization has been made possible in 3a43ade6e8b9df7c06eb8b7c144e06d21a933f7a. As an example, a Dutch locale has been added in 6ff2bbef6cd709dd1558c7ed4844165685d93cdb.

@ddarfantasy and @ashed, feel free to translate the app based on https://github.com/Mosc/Glider/blob/master/lib/l10n/app_en.arb.

Some opinionated guidance, which you can ignore as you see fit:

- Do make sure the `@@locale` value matches the one in the filename.
- Do not copy over the keys prefixed with a single `@`, they are only needed in the source language.
- Do prefer liberal translations over literal translations if it helps make the words and sentences feel more natural.
  - The `wittyError` in particular is used to lighten the mood when an error occurs, so a pop culture reference appropriate for your language works best. A well-known [Westworld](https://en.wikipedia.org/wiki/Westworld_(TV_series)) quote is used in English. The Dutch translation uses a sentence uttered in an iconic [children's show](https://en.wikipedia.org/wiki/Bassie_%26_Adriaan) when something goes wrong.
- Do resist using English terms as long as it doesn't make the translation too contrived.
- Do try to get the app to run locally to get a sense of what your translation looks like in practice. Contact me if you're having issues.
- Do try to offer the translation through a pull request. Contact me if you're having issues.

**Comment by ashed** [comment]
[Glider-ru.zip](https://github.com/Mosc/Glider/files/6857340/Glider-ru.zip)
Russian translation - Glider-ru.arb.zip
Add it to upstream, please.

**Comment by Mosc** [comment]
Hey, thanks for the effort. Would you mind offering it as a pull request? It's a more fitting style of collaboration compared to exchanging ZIP files, and will make it easier to review changes in the future. As mentioned, I would also prefer it if you did not include the lines prefixed with a single `@`. Have you checked the changed locally to see what they look like in practice?
