### ISSUE TITLE
Question: Why can frowning face emoji can be rendered

### ISSUE THREAD

**Issue by Fintasys** [Mosc/Glider#170]
Hey, great App and thanks for your efforts !

I'm doing some investigations how `frowning face` ☹️ emoji can be displayed without using `NotoColorEmoji` font from GoogleFonts. I checked your app and could see that it renders the emoji correctly. My app and other Flutter apps can't render it correctly, so I looked into your code to find out how you did it. I wasn't able to figure it out, so I wonder if you knew why.

I would appreciate your help. 
Thank you!

**Comment by Mosc** [comment]
That is certainly an unusual question.

It would help to provide a bit more detail on this. You're not really making clear what not rendering "correctly" means in this context. Additionally, where are you seeing that specific emoji? In a Hacker News story? In a comment? Are you typing it yourself in a search field, or in a text field somewhere else? Screenshots welcome.

Does anything change if you select a different font on the settings page?

If you're looking to compare this app's font usage to other's, consider looking at the following:

- The font definition in the `pubspec.yaml`
- The call to `GoogleFonts` to retrieve the `TextTheme`
- The Flutter version used (Glider typically updates to the latest beta version ASAP)

**Comment by Fintasys** [comment]
Thanks for your comment 🙇
I'm creator of the FlutterEmojiPicker package and I'm investigating how to display some emoji correctly, like frowning face.
I checked other flutter apps and noticed that all of them aren't able to display it directly without using a custom emoji font. So far, me and other contributor assuming that flutter can't access the native fonts for some reason. Only yours was able to display it in search bar for unknown reasons 🤔 

Glide 

![Screenshot_20240110-122720_1.png](https://github.com/Mosc/Glider/assets/11667234/b6c99cf1-2d67-4d5d-9ec0-6cec26d1ce6d)

Regular flutter app

![Screenshot_20240110-122829.png](https://github.com/Mosc/Glider/assets/11667234/2f354139-96ef-4dbe-b317-cab061a7fcef)

I also tried using the same notoSansTextTheme but  same issue.

**Comment by Mosc** [comment]
Well, I did already list some ideas...

First one that I tried was the Flutter version, and indeed, that turns out to be the difference maker. Starting from 3.18, Flutter appears to render the offending emoji fully colorized.

I'm considering this case solved.

**Comment by Fintasys** [comment]
I didn't took Flutter version into consideration. But you were right, the issue is indeed solved by 3.18. Thank you very much and sorry for the inconvenience 🙇
