### ISSUE TITLE
Give a few serif fonts as option

### ISSUE THREAD

**Issue by debnath-d** [Mosc/Glider#186]
I find reading text in serif fonts easier. It would be great if you provide a few serif options. I personally like [Source Serif 4](https://github.com/adobe-fonts/source-serif) and [EB Garamond](https://github.com/georgd/EB-Garamond). TeX Gyre Pagella is also another great serif font.

Allowing custom fonts from local ttf/otf files is also a reasonable solution.

Edit: Also wanted to mention

- [Libre Baskerville](https://github.com/impallari/Libre-Baskerville)
- [Crimson Pro](https://github.com/Fonthausen/CrimsonPro)
- [Bodoni*](https://github.com/indestructible-type/Bodoni)

**Comment by Mosc** [comment]
Sure. I've added your first two suggestions, along with some serif pairings for existing inclusions, in b23757737498e2cfcbd18387f1b3325653afa1b2. Let me know if there's another you _really_ want included, but I'd also like to prevent the list from feeling overwhelming. Allowing local font file selection is probably possible but I consider it not worth the effort.

**Comment by debnath-d** [comment]
Can you please also add [Crimson Pro](https://github.com/Fonthausen/CrimsonPro)? It's a beautiful font!
