### ISSUE TITLE
Feature Request: Top Level Comment Navigation

### ISSUE THREAD

**Issue by kigero** [Mosc/Glider#19]
One of the things that I've become accustomed to in my reddit client (Joey) is the comment navigation.  At the bottom of the comments view is a navigation toolbar, the center lets you select how to navigate (with lots of options, but I really only use top level), and the arrows navigate up or down between comments.  So if I start reading through a comment thread and get bored, I can quickly go to the next top level comment and start reading that one.  It would be great if something similar could be added to Glider.  Some other clients that I've looked at use the volume buttons for this sort of navigation, but I prefer something on screen.

![image](https://user-images.githubusercontent.com/679688/120002797-28cc8a80-bfa3-11eb-9ef1-553abd101d0a.png)

**Comment by Mosc** [comment]
The best I can promise you right now is that I'll consider it! I'm currently mostly focusing on features that do not add any additional configuration for the users, and this is not a feature I would want turned on by default.

**Comment by kigero** [comment]
No worries, that sounds good to me.  I can appreciate that it's a pretty niche feature.  Thanks!

**Comment by vonDubenshire** [comment]
I hope someone can get this to work over day.

I just installed the app, got it all set up and then realized that was the one feature I suddenly needed really badly!

**Comment by Mosc** [comment]
This has been implemented as part of v2.0.0!
