### ISSUE TITLE
Can't change appearance settings (anymore?)

### ISSUE THREAD

**Issue by otaconix** [Mosc/Glider#29]
I recently updated to version 1.9.2 from the F-Droid repo, and I noticed the theme switched to the light one. Turns out the app now follows the system, which is a nice feature. 

However, I prefer the dark theme at all times, but unfortunately, I can't switch any of the settings in the Appearance panel. Tapping any button or toggle triggers an animation to let me know I indeed tapped it, but otherwise nothing happens.

**Comment by Mosc** [comment]
Hey, not sure what could be causing that. Does any other functionality with persistence work, such as favoriting? How about logging in (uses different, encrypted storage)?

**Comment by Mosc** [comment]
I'm assuming this has been fixed with 900f42259dca803978752ae7d0d7a8cb40d85f29. If the problem still occurs in the new release, feel free to comment.

**Comment by igoralmeida** [comment]
Is it not possible to keep a dark theme _despite_ the system settings, though?

**Comment by Mosc** [comment]
> Is it not possible to keep a dark theme _despite_ the system settings, though?

Not at the moment. I assumed it always made sense to follow the system setting, but clearly there are madmen who like to customize this per app. There's a good chance a light/dark mode setting may return.
