### ISSUE TITLE
Cannot collapse comment trees anymore

### ISSUE THREAD

**Issue by HalosGhost** [Mosc/Glider#30]
Model: Pixel
Android: 10
ROM: Lineage OS 17.1

Hello, as of version 1.9.2 I cannot tap on a comment thread to expand/collapse it anymore. I've since reverted back to 1.9.1 and expand/collapse works as-expected.

Let me know if there is more useful information I can provide. Thank you for your work!

**Comment by Mosc** [comment]
Interesting! I think this actually has the same underlying problem as #29. I can't reproduce either issue though. Something seems to be broken with actions that require saving to shared preferences, but I'm not sure what could've caused that between v1.9.1 and v1.9.2. 900f42259dca803978752ae7d0d7a8cb40d85f29 may have fixed it, so do you mind testing [this APK](https://github.com/Mosc/Glider/files/7138026/Glider-2cf08b3.zip) before I release a new version?

**Comment by HalosGhost** [comment]
That APK you linked does not appear to have the same issue for me. Namely, it seems I can indeed collapse comment threads as-expected. 👍

**Comment by HalosGhost** [comment]
If it matters, the theme stayed dark for me throughout switching to 1.9.2.

**Comment by Mosc** [comment]
Great, thanks. Weird that your problem was different from the other issue but that they're both occurring when the app is trying to save to shared preferences. Oh well, seems to work now and I'll push forward with a new release.

**Comment by KyleFN** [comment]
Fwiw I've had the same issue being unable to collapse comment trees happening most of the time with this latest version, a restart or two usually fixes it though.
