### ISSUE TITLE
Reply sliding gesture colides with Android 11 back gesture

### ISSUE THREAD

**Issue by riedel** [Mosc/Glider#32]
It is nearly impossible for me to use the app when using gesture navigation on Android 11. I always trigger a reply when I want to just go back. I have no clue how other apps handle this but glider is the first app where I see this problem and it is driving me crazy.

**Comment by erahhal** [comment]
This is something that happens 100% of the time with me.  It's also the first and only app I've seen this problem with.

Gmail has swipe right and left and it doesn't conflict, so either they've figured out how to cancel the in-app swipe gesture if there's a navigation swipe gesture registered, as suggested above, or they don't register the swipe if it comes from the very edge of the screen. 

In any case, it's almost unusable as is.  It's a nicely designed app and the best HN client I can find for Android besides this issue.

**Comment by Mosc** [comment]
It's not a perfect solution, but thanks to @shambu2k with his work on #38 you'll be able to disable gestures within the app entirely in the next release. This should at least be good enough to work around this issue.

It's interesting that the severity of the issue differs so much between users. I'm using gesture navigation on a new phone and I'd say this scenario occurs maybe once out of a hundred swipes.

**Comment by erahhal** [comment]
I have a OnePlus 7 pro with LineagoOS.  I have a couple theories as to what might be making it worse:

1. Custom OSes (e.g. OxygenOS that comes with OnePlus phones have the swipe navigation finely tuned). AOSP distributions like Lineage are generic implementations of swipe

2. The OP7Pro has a curved screen, which makes swiping from the very edge super easy and typical. A Pixel with a flat screen and a thick case will cause the user to start a swipe further away from the edge, potentially making this problem occur less frequently.

**Comment by Mosc** [comment]
Closing this because while the bug still exists, it is a subset of the problem described in #36. Updates can be tracked there.
