### ISSUE TITLE
Synchronizing fails when triggered manually from the accounts page

### ISSUE THREAD

**Issue by solaremperor** [Mosc/Glider#35]
When I hit the "synchronize" button inside the settings page, I get a prompt informing me that all favorites added before logging in would be overwritten. When I hit OK, I receive a message saying "Synchronizing failed" and my favorites from my HN account (note that while I have a new account, I do have unsynced favorites). Here is a [screenshot](https://imgur.com/a/8Y2IOZg).

This has been happening all day yesterday. However, when I opened the app this morning, my favorites did populate. So, it seems like it's only the manual sync that seems to be a problem.

**Comment by Mosc** [comment]
Hey. Glider doesn't perform any automatic synchronization (from the Hacker News server to the app), so if you do see a populated favorites page, I'm guessing those were successfully processed during your manual attempts. Is it a complete list, or do you have multiple pages of favorites and/or upvotes in your profile and is only some of it synchronized?

There's no official API to retrieve favorites and upvotes, so Glider scrapes the website to do so. I've seen the website return a HTTP 503 error with the message "Sorry, we're not able to serve your requests this quickly." when quickly trying to quickly load several pages. I'm planning on adding a retry mechanism that should at least back off for a bit on this specific error, and may also help to alleviate other issues.

**Comment by Mosc** [comment]
I'm considering this fixed with 27a3426727a9bf8b266a0e5aa3989e7730abb825. Feel free to let me know if it's still broken in the upcoming release.

**Comment by solaremperor** [comment]
I haven't seen any update on the play store today but favorites (from the website) don't update when I pull down to refresh the page. Also, neither my favorites nor my comments don't sync either when I hit the synchronize button the account page.

**Comment by Mosc** [comment]
Yeah, the update was in review for a while but should be available now. For the record, refreshing the favorites page doesn't actually pull new favorites from the website, it just refreshes the favorites that are stored locally.
