### ISSUE TITLE
Android gesture navigation interfering with in-app swipe navigation

### ISSUE THREAD

**Issue by shambu2k** [Mosc/Glider#36]
Sometimes, swiping from the left when in news page, it goes back to the feed and also closes the app. (Screen recording below)
@Mosc already pointed out that this could be due to flutter/flutter#83087
Reducing the gesture detection width definitely reduces the frequency of this happening.
This is probably the same issue causing #32 but this is what happens.
https://user-images.githubusercontent.com/49567934/140781994-9fa7c416-ac6d-4a98-b1b2-86b7688cd628.mp4

**Comment by Mosc** [comment]
Yeah, thanks for reporting this bug. At the moment the only workaround I can imagine is to add a settings that disables some or all gestures. Not really a fan of that, but it might just be necessary.

**Comment by shambu2k** [comment]
I have some experience with flutter. I could try working on this. Do we add the gesture toggle in the appearance bottom sheet?

**Comment by Mosc** [comment]
Oh, sure, a PR would be welcome. I think we'd put the swipe disable toggle in the new Settings menu, as its effect is not directly visible to the user.

**Comment by Mosc** [comment]
Although certainly not a perfect solution, I've decided to abandon gestures entirely starting from v2.0.0 due to their general bugginess.
