### ISSUE TITLE
Feature request: Clear clicked stories

### ISSUE THREAD

**Issue by joshcangit** [Mosc/Glider#39]
Stories remain greyed after being tapped.

The only way to reset this is to clear this app's data in system settings.

I feel there should be an easier way to clear clicked stories.

[Harmonic](https://play.google.com/store/apps/details?id=com.simon.harmonichackernews) has this feature.

That app is pretty good but I prefer to use this.

**Comment by Mosc** [comment]
Hey. Wouldn't you much rather have an option to disable fading read stories in the first place, or is there some other use for clearing visited stories that I'm missing?

**Comment by joshcangit** [comment]
> Hey. Wouldn't you much rather have an option to disable fading read stories in the first place, or is there some other use for clearing visited stories that I'm missing?

I was thinking it should just clear visited stories.

Now I'm not sure it should be implemented since this is a pretty minor feature.
Harmonic seems to be designed to be feature-rich.
If Glider's design is meant to be minimal then maybe this can be ignored.

**Comment by Mosc** [comment]
You're right that Glider's designed to be more minimal, but that doesn't necessarily mean that I'll refuse to add options. I've (reluctantly :smile:) implemented several requests in the past because I can see their value for some people. I'm still curious therefore, what would you actually use a 'fresh start' in visited stories for? Wouldn't the frontpage just look similarly visited again a few days later?

**Comment by ynotzort** [comment]
Hey! I just created a PR for toggling the visited state for single stories (https://github.com/Mosc/Glider/pull/74) . At least my use case is that sometimes I accidentally click on a story that I would want to read in the future but not right now, and having it marked as visited annoys me.

**Comment by Mosc** [comment]
This has been implemented in 9ffb61018f76691ce2670575fc3935221222e357, along with the previously present toggling of visited status that got lost in the big rewrite.
