### ISSUE TITLE
Feature request: scrolling into view when collapsing comment.

### ISSUE THREAD

**Issue by sergilazaro** [Mosc/Glider#4]
First off, great app, almost everything is just right!

I've noticed that when you collapse a long comment, if the beginning of the comment was out of view, way off to the top, then after collapsing the comments below it scroll up and you can lose track of your previous location, and have to scroll up manually.

I think a better behavior would be: if the new bounding rect of the just collapsed comment is not 100% in view, scroll just until it's fully in view.

I would try to implement this myself but I have zero experience with the language and Android development in general.

**Comment by Mosc** [comment]
Thanks, sounds useful! It should be possible to implement this in Flutter using [Scrollable.ensureVisible](https://api.flutter.dev/flutter/widgets/Scrollable/ensureVisible.html) with [ScrollPositionAlignmentPolicy.keepVisibleAtStart](https://api.flutter.dev/flutter/widgets/ScrollPositionAlignmentPolicy-class.html), but... upon trying it just now I couldn't get it to work correctly. It would recognize whether the top part of the comment was visible, but attempt to fix that by scrolling all the way to the top of the page.

I'll revisit this in the near future.

**Comment by Mosc** [comment]
Will be present in the next release.

For the poor soul Googling the same problem I experienced before, here's a brief explanation of what went wrong. [Scrollable.ensureVisible](https://api.flutter.dev/flutter/widgets/Scrollable/ensureVisible.html) triggers on _every_ scrollable in the context's tree. That normally works fine, unless you have more than one, like the SliverList within the CustomScrollView in this project. This resulted in the animation also triggering on the CustomScrollView, which flung us right to the top of the SliverList. Instead, [ScrollPosition.ensureVisible](https://api.flutter.dev/flutter/widgets/ScrollPosition/ensureVisible.html) (interally used in Scrollable.ensureVisible) allows us to only target the closest scrollable in the tree.
