### ISSUE TITLE
Feature Request: show parent comment

### ISSUE THREAD

**Issue by azizLIGHT** [Mosc/Glider#42]
Deep in a comment chain, it can sometimes get difficult to keep track of who replied to who and about what. For threads with multiple lengthy replies, at the same tree depth, and of a technical and wordy nature, being able to see the parent comment without scrolling up would be convenient. It could prevent scrolling up to reread the parent comments and scrolling back down to find the comment you were on. 

Here's an example on a reddit client with a short comment tree to illustrate this feature:
![Screenshot_20220127-034501](https://user-images.githubusercontent.com/8013867/151325009-01d0d4bc-2b4f-4f96-a6bd-291967257adb.png)

Hitting the up arrow could show the n-1 parent in successive steps upto the GP like this:
![Screenshot_20220127-034852](https://user-images.githubusercontent.com/8013867/151325284-22728cd0-f543-4014-ac1f-5032bfafa0a0.png)
Each successive press leads to the n-1 parent of the shown comment: 
![Screenshot_20220127-034930](https://user-images.githubusercontent.com/8013867/151325902-dc8e2796-6158-4fc4-8136-f64906bd69f0.png)
![Screenshot_20220127-035844](https://user-images.githubusercontent.com/8013867/151325933-987530d3-a0e1-4531-a11e-75814324b532.png)
Until the final parent is shown (Comments at sibling depth are skipped since they are not direct parents, and unrelated)
![Screenshot_20220127-035852](https://user-images.githubusercontent.com/8013867/151325960-c25257b6-03c2-46ac-aaa0-5be30576301f.png)

Or it could show them all at once. The order could be reversed if it makes sense.
![Screenshot_20220127-034542](https://user-images.githubusercontent.com/8013867/151326035-2eaec725-63e0-42c8-b637-e39c9cdf69eb.png)

This is with a simple example, so it would shine in a complicated thread with many replies in a specific depth and the parents are harder to find and keep track of when manually scrolling up/down

It could be optional by explicitly needing a setting to enable it so that it doesn't clutter the UI: 
![Screenshot_20220127-035031](https://user-images.githubusercontent.com/8013867/151327067-eed11eab-b975-49ad-99c6-a54749b28d31.png)

There's a natural spot for an 'up button' in each comment's context menu next to the upvote, reply, favorite, flag, share buttons. I think the feature from the reddit client translates well into HN, but I'm not sure of the implementation and options and code. In any case, these were some ideas, and I hope you consider this feature in whatever implementation that makes sense for Glider and HN. Thank you.

**Comment by Mosc** [comment]
I like it. I've experienced the same difficulty following a long discussion, and this seems like an elegant solution.

**Comment by Mosc** [comment]
Implemented in da3b4b6ce7cf8bd328ea3f8c1dd45f1bfe01eba6 and should be part of the next release. I've chosen the option where one parent is shown in the dialog and the user can manually continue navigating to earlier ancestors, I found displaying the entire thread in a dialog at once to be an overload of information, probably because Hacker News comments are typically longer than Reddit comments, which in many cases necessitated a significant amount of scrolling.
