### ISSUE TITLE
Feature Request: Embed thread title when using "Share" button

### ISSUE THREAD

**Issue by AB1908** [Mosc/Glider#43]
Currently, the share functionality seems to share only the thread or article link, as opposed to how Materialistic does it. I'll add screenshots upon request. Is it possible to add that functionality in? I took a look at the codebase but sadly, Java (and especially Android) seems beyond me for now.

**Comment by AB1908** [comment]
Hi, thanks for the response. I think the first is enough as sharing the thread into Orgzly doesn't populate the "Title" field.

**Comment by Mosc** [comment]
I've confirmed that the previously mentioned code change fills the title field in Orgzly, so that should be present in the upcoming version.

**Comment by AB1908** [comment]
Thanks a lot! Excited for the next release! I've found some other performance slowdowns and I'm considering learning how to do Android stuff at this point haha.
