### ISSUE TITLE
Feature request: Pagination instead of infinite scroll

### ISSUE THREAD

**Issue by williamtheaker** [Mosc/Glider#46]
Inspired by [My lizard brain is no match for infinite scroll](https://alexanderell.is/posts/infinite-scroll/) (via Hacker News)

**Comment by Mosc** [comment]
An interesting request and I appreciate the Hacker News story angle of it. I can't even recall an app with manual pagination, which I guess speaks to the ubiquitousness of infinite scrolling. I've received a similar request through email a while back, which I may have dismissed too quickly as not being a good fit for an app. Although I'm still not sure what the user interface should even look like, I'm growing more sensitive to the argument of reducing addictiveness of apps in general. The aforementioned email sender also suggested adding post numbering to help them keep track of time.

**Comment by williamtheaker** [comment]
It's been a long time, but I think this had pagination: https://f-droid.org/en/packages/com.manuelmaly.hn/

**Comment by Mosc** [comment]
Implemented in 1170ab9749df55422f59b054135f6eed14f0e7f2, eebf815e939744f55e24f406f4c0e9e175c21ec8 and ce42066a5a4e360dd75fe55c4c465da3e56fe323 as part of the upcoming release v1.15. If infinite scroll is disabled, stories, favorites and user submissions are paginated with a page size of 30, just like the Hacker News website homepage. Comment threads are not paginated for now.
