### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by williamtheaker** [Mosc/Glider#48]
Thanks for adding my feature requests in #45 and #46; the new build just landed in F-Droid. Do you have any plans to add a link for users to donate to support development of this app?

**Comment by Mosc** [comment]
I'm not accepting donations at this point. Money has a tendency to complicate things, especially in terms of expectations. Not saying that would necessarily apply to you, but keeping it simple is better for this project.

The gesture is greatly appreciated though.
