### ISSUE TITLE
Suggestion: release on F-Droid

### ISSUE THREAD

**Issue by An4cl3t0** [Mosc/Glider#5]
Hi, fantastic app! It would be perfect if someone could download this on F-Droid repos without relying on google play.
Thanks for your work.

**Comment by Mosc** [comment]
Yeah, that'd be nice. It seems I'd need to submit a merge request to the [fdroiddata](https://gitlab.com/fdroid/fdroiddata) repository with an appropriate F-Droid metadata YAML that also describes the build steps. And, although not strictly required, adding a Fastlane file structure to Glider looks to be [highly recommended](https://gitlab.com/snippets/1895688) for automatic metadata updates. I do want this F-Droid release to happen, but it'll take some time to figure out the full process.

**Comment by Mosc** [comment]
I've started to look into this in a bit more detail. Roadmap:

- [x] Introduce fastlane structure
- [x] Write F-Droid build YML
- [ ] Test F-Droid build locally
- [ ] Create tagged release that includes the fastlane structure (possibly a v1.6.1)
- [ ] Create merge request for inclusion in F-Droid data repository

Currently stuck on testing locally, as any `flutter pub run` tasks initiated by `fdroid build` on my WSL2 instances appear to just... freeze.

**Comment by Mosc** [comment]
Glider has been [merged](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8872) into the F-Droid data repository! It'll take a few days to show up, after which I'll promote it in the readme and close this issue.

**Comment by Mosc** [comment]
Closed in 239a62aea0b39f2dd2841bc9f080d26d50914278.
