### ISSUE TITLE
Feature Request: Open article as default

### ISSUE THREAD

**Issue by anyone27** [Mosc/Glider#50]
Would you consider an option to have links open as default rather than comments?

**Comment by Mosc** [comment]
The app does offer other quick ways to open the link by either tapping the favicon on the right, or by swiping left on the tile (assuming a left-to-right script). I also like the fact that opening comments by default makes the behavior of link posts and text posts more consistent.

In general I would not be a fan of adding such a setting, but then again, I think you'll find in this repo's issues that I've been persuaded in the past. :) Would you say the mentioned ways of opening a link are not sufficient?

**Comment by Mosc** [comment]
Thanks! Glad to hear the mentioned features fit your workflow. I'll close the issue for now.

Tips on how to highlight features like these are welcome. Actions being hidden behind horizontal swipes is mentioned in the walkthrough on the first app launch, but indeed, this specific interaction may not be clear. I've also seen tappable thumbnails in Reddit apps before, but I can imagine that is not an obvious interaction if you're not familiar with it.
