### ISSUE TITLE
Feature request: move "Settings" and "Appearance" to a single menu

### ISSUE THREAD

**Issue by ghost** [Mosc/Glider#52]
This way the users not familiar with the app will find the needed parameters easier

**Comment by Mosc** [comment]
The combined bottom sheet would take up a lot of space on many devices. I like the effect of seeing the result of changing appearance settings instantaneously. Having said that, I do think you're right that combining the appearance and settings menu items is the way forward.

**Comment by brownshark1993** [comment]
I think it could be a fullscreen menu accessible from the 3 dot icon

**Comment by Mosc** [comment]
This has been implemented in 8c07b880d137e294d2844cee5567ea9d351b500a.
