### ISSUE TITLE
Feature request: add an "About" section in the 3-dot menu

### ISSUE THREAD

**Issue by ghost** [Mosc/Glider#53]
This section could contain a link to this GitHub repo and some other information

**Comment by Mosc** [comment]
Sure. What other information would you like to have available? Could also just be a part of the hypothetical settings page I theorized in #52 rather than a menu item.

**Comment by brownshark1993** [comment]
Your (user)name, year and version, for example

**Comment by Mosc** [comment]
Implemented in adc17d4df979dca9a70c4b657234c88104e1f747 with some data and links that I thought would be useful.
