### ISSUE TITLE
Bug: in-app gestures are incompatible with Android gesture navigation

### ISSUE THREAD

**Issue by ghost** [Mosc/Glider#55]
For example, when you swipe from the right edge of the screen to the left, it triggers both in-app gesture and systemwide gesture. This could be solved by limiting in-app gestures to only the centre of the screen

**Comment by Mosc** [comment]
Yes, this is a known issue. The "use gestures within the app" setting exists as a workaround for now. Closing because it's a duplicate of #32 and #36.
