### ISSUE TITLE
Have to scroll horizontally endlessly for quotes

### ISSUE THREAD

**Issue by tiklii** [Mosc/Glider#56]
See: https://news.ycombinator.com/item?id=31025660

**Comment by Mosc** [comment]
The referenced quote is prefixed with at least two spaces, which according to Hacker News's [formatting documentation](https://news.ycombinator.com/formatdoc) means it should be produced verbatim and is intended for code. Yes, we could easily choose to word wrap such a section, but that would severely mess up rendering of code blocks. I would argue this is a misuse of the "verbatim" formatting option and that there is no sane way for Glider to handle such an occurrence. Let me know if you have ideas for improvement.

**Comment by Mosc** [comment]
Because the website has at some point changed its behavior into wrapping these elements, Glider now also wraps these elements since 55970ad71b63f76b75d86eb927e15345097d457a.
