### ISSUE TITLE
Feature request: Setting to hide posts with certain words in the title

### ISSUE THREAD

**Issue by reeseovine** [Mosc/Glider#57]
There are some posts throughout HN covering ...certain topics... that are of zero interest to me, so instead of scrolling past them it would be nicer to be able to hide them altogether with a muted keyword list, similar to Twitter's mute word feature.

Would also be nice if this supported regular expressions but it's not totally necessary for my use case.

**Comment by Mosc** [comment]
It took some time to arrive, but a word filter has been added in v2.6.0 with 25382f54832a1b4f91249852d036bfd04ff05321. It's a pretty naive implementation so far, without regex support.
