### ISSUE TITLE
Feature request: Customizable text selection context menu

### ISSUE THREAD

**Issue by scubajeff** [Mosc/Glider#62]
After version 11, Android changes package visibility behavior, to allow other apps, like translator, wikipedia, to add custom actions when user select text in Glider, please add the following to it's manifest:

<queries> <intent> <action android:name="android.intent.action.PROCESS_TEXT" /> <data android:mimeType="text/plain" /> </intent> </queries> 

Refer to https://developer.android.com/training/package-visibility/use-cases#custom-text-selection-actions

**Comment by Mosc** [comment]
Sounds like a nice little addition for almost no effort, but I don't think this is actually possible in Flutter at this point! The [ToolbarOptions ](https://api.flutter.dev/flutter/widgets/ToolbarOptions-class.html) class only allows for a limited set of actions and adding the `query` you referenced to the Android manifest doesn't change the situation, unfortunately. If the Flutter framework ends up supporting this feature down the road I'd be totally willing to add it to Glider, but I'm closing the issue for now.
