### ISSUE TITLE
Feature - replies(inbox)

### ISSUE THREAD

**Issue by FarisZR** [Mosc/Glider#66]
Thanks for the awesome app!
A feature that its really missing is an Inbox / replies to my comments / Posts.

I use Hacki just for this even though I prefer Glider.

**Comment by Mosc** [comment]
Creating a page like this is very doable. Unlike in Hacki though, I'm not planning to add any background refresh and notifications at this point.

**Comment by FarisZR** [comment]
I never noticed Hacki has background refresh, maybe its only on IOS.

**Comment by Mosc** [comment]
This has been implemented in edf92100ff8acba67b691d372f49feb49ccbf17e in the form of an inbox page.

**Comment by FarisZR** [comment]
When is the update with this feature coming out?
Is there a specific release schedule?

**Comment by Mosc** [comment]
There's no defined release schedule. I just create a new release when significant enough changes have been made, and when I feel that I've personally tested those changes well enough. Should be Soon™! If you'd like to try out a newer build you're welcome to sideload an APK generated by the CI build under the Actions tab.
