### ISSUE TITLE
Feature request: Android 13 Adaptive Icon

### ISSUE THREAD

**Issue by danielcherubini** [Mosc/Glider#71]
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive#add_your_adaptive_icon_to_your_app

Seems like just adding a new line to `res/mipmap-anydpi-v26/ic_launcher.xml` will be enough. 

Thoughts?

**Comment by Mosc** [comment]
Normally I would just leave all the icon business to [flutter_launcher_icons](https://pub.dev/packages/flutter_launcher_icons), but given that it's not supported in their generator and it's a very minor manual change, I added the one-line change in 6d39db6d469d30b57c500264063d940ba75caa5a. Thanks.
