### ISSUE TITLE
UI glitches out and becomes unreadable on Android 11

### ISSUE THREAD

**Issue by lightspot21** [Mosc/Glider#72]
Hello,

The latest version (1.17.1) from F-Droid glitches out like this on Android 11:

![Screenshot_20220816-225732_Glider](https://user-images.githubusercontent.com/30842999/184973286-0129e154-c773-4ac1-8e0d-9b4df8cdd93c.png)

This does not occur on the previous F-Droid release (1.17.0).

Running on Xiaomi Mi 10T Lite (`gauguin`) with LineageOS 19.1 (with microG).

**Comment by Mosc** [comment]
Not sure what's going on here, as I cannot replicate it. Does this consistently occur, also at different times when the story list has changed?

**Comment by ridv** [comment]
I was able to reproduce this after upgrading to 13. What fixed it for me was clearing cache and data.

**Comment by Mosc** [comment]
Good to know! I'm still not sure what exactly causes this, but that workaround suggests the presence of some corrupt saved data and/or the app not handling specific saved data well.
