### ISSUE TITLE
Feature request: Add About and OSS Licences Page

### ISSUE THREAD

**Issue by riedel** [Mosc/Glider#73]
I just noted when looking for the GitHub link from the installed app, I found no About page that links to this GitHub (FDroid has it so not much of hassle)

Also IMHO it would be good to include also an OSS Licences page. It is debatable if it is strictly necessary for MIT licenses but a good practice.

See this flutter package:
 https://github.com/espresso3389/flutter_oss_licenses

Not critical at all.

**Comment by Mosc** [comment]
Coincidentally, earlier today I had just added an about section to the settings page with a link to this GitHub page in adc17d4df979dca9a70c4b657234c88104e1f747. That did not include a page with licenses of the packages that are used, so I've appended a link to such a page in 3ab9dcded869c7b51af232d3cf8cc76de1754525. To keep it simple (although very uncustomizable) I'm just relying on Flutter's built-in `showLicensePage` here.
