### ISSUE TITLE
Allow for downvotes?

### ISSUE THREAD

**Issue by emacsomancer** [Mosc/Glider#78]
It would be convenient to be able to have a downvoting option. (I note that Hacki has this feature.)

**Comment by Mosc** [comment]
Would be a nice addition. A slight complication is that downvoting is not available for users until they reach 501 karma, and the app currently does not keep track of a logged in user's karma count.

**Comment by emacsomancer** [comment]
Maybe a minimal solution could be to have it as an "opt-in" feature in the settings, with a warning about it not working in the case of having under 501 karma?

**Comment by Mosc** [comment]
Implemented in 1c5c896179985b9cb4294794fd9cf66775a0b2ef with an opt-in setting.
