### ISSUE TITLE
Feature request: Add more lists to the filter dropdown

### ISSUE THREAD

**Issue by TobiWaterfield** [Mosc/Glider#80]
First of, I love the app and use it every day, so thank you!

I think it would be really neat, if the filter list dropdown had a few more options. Especially /active is very convenient if you like to follow the active discussions.

Currently in the app: Top, New, Best, Ask, Show, Jobs.
All the available options: https://news.ycombinator.com/lists

Best regards

**Comment by Mosc** [comment]
Unfortunately, those lists are not offered through the [Hacker News API](https://github.com/HackerNews/API#live-data), That doesn't mean it's impossible to retrieve them of course, but I do try to prevent having to scrape the website whenever I can.

**Comment by TobiWaterfield** [comment]
Ahh, that makes sense. Thanks for the quick follow-up and, once again, for the excellent app! :)
