### ISSUE TITLE
Comments go crazy when comments above load

### ISSUE THREAD

**Issue by rbits0** [Mosc/Glider#84]
When I collapse a comment and then try to read the comment below it, and the comment I collapsed loads a bunch of replies, the comments go crazy and I can't read anything. 

Video: https://i.imgur.com/SW2SIVr.mp4

Kind of makes the app unusable, which is a shame because I haven't found another app with the catch up feature.

**Comment by zanovis** [comment]
I've had this happen a few times but I'm not sure how to repeat

**Comment by Mosc** [comment]
This should be fixed as of v2.0.0!
