### ISSUE TITLE
Quoted text surrounded by many quote blocks and appears as a 1-character-wide column of text

### ISSUE THREAD

**Issue by azizLIGHT** [Mosc/Glider#85]
The quoted text looks like it is surrounded by many successive shaded backgrounds. The text is one character wide and requires unnecessary vertical scrolling to traverse past it. This may be an edge case due to how the commentator formatted the text:
https://news.ycombinator.com/item?id=35052644
version 1.18.1
![Screenshot_20230307-223847](https://user-images.githubusercontent.com/8013867/223614978-4783ad66-9d04-486b-bf99-6bfdfc2e0734.png)

**Comment by Mosc** [comment]
Definitely a bug, and fixed as of v2.0.0. Although I would argue that this actually looks awesome.
