### ISSUE TITLE
Scrolling issues in HN comments 

### ISSUE THREAD

**Issue by Tintedfireglass** [Mosc/Glider#86]
1.When comments have been collapsed before all the subcomments load the UI goes into a frenzy trying to load and simultaneously collapse the thread making it unusable for a minute or so if your internet is slow

video :

https://media.discordapp.net/attachments/884641872008577064/1087443576511807599/screen-20230321-000156.mp4

2.Even when not collapsed the new loaded threads when loaded scroll the thread down making it unusable for slow internet connections

video :

https://media.discordapp.net/attachments/884641872008577064/1087444711704375377/screen-20230224-181640.mp42.mp4

as both issues are basically the same I combined them into one issue

I'm not sure how a workaround could be possible as the app is fundamentally designed in such a way that this is bound to occur. 

thanks 
:)

**Comment by Mosc** [comment]
Closing this for now. The first mentioned issue has been resolved, and the second issue, we've determined, is kind of inherent to the way comment trees are loaded. Still open to alternative suggestions though.
