### ISSUE TITLE
Feature Request: Collapse comment (& it's children)

### ISSUE THREAD

**Issue by tennox** [Mosc/Glider#87]
Often a certain sub-comment doesn't interest me, so I want to skip past it (and all it's children), but I don't see a way to easily do that.

**Comment by gekoke** [comment]
> Often a certain sub-comment doesn't interest me, so I want to skip past it (and all it's children), but I don't see a way to easily do that.

Tap on a comment's body to collapse the comment

**Comment by tennox** [comment]
Oh wow... thank you 😅🤘
