### ISSUE TITLE
Inbox not loading

### ISSUE THREAD

**Issue by riedel** [Mosc/Glider#93]
Don't know if there was an apo change recently but my inbox stopped loading.

Can anyone else confirm this?

**Comment by Mosc** [comment]
Update v2.0.0 was just released. Could you confirm whether or not the bug still occurs there?

**Comment by Mosc** [comment]
Thanks for the confirmation. I believe this is the result of this page trying to request too much data at once, causing Algolia to generate an internal server error. Will limit the amount of IDs this page queries replies for.

**Comment by Mosc** [comment]
c9aa0db41dbb4d377239e6be8f2c93fde0b94181 should fix this, released as part of v2.1.0.
