### ISSUE TITLE
Password manager autofill/pasting in new HN login page

### ISSUE THREAD

**Issue by joaommartins** [Mosc/Glider#97]
After the new update, when attempting to login to my HN account the UI does not allow to paste text into the field nor triggers autocomplete suggestions in Gboard. 

Thanks for the update, enjoying the new design!

**Comment by mon-jai** [comment]
It works for me.

![Screenshot_20231024-095813~2](https://github.com/Mosc/Glider/assets/91261297/1ecf6b76-614f-4110-a7f9-2188f8df0ce1)

**Comment by Mosc** [comment]
It's not working for me either, but I'm not really sure why. As far as I can tell autofill should be possible even within Flutter webviews, and @mon-jai's result shows that it is not inherently broken.

**Comment by joaommartins** [comment]
Commenting with some more details, I'm running Android 14 on a Pixel 7 Pro, with Glide installed directly with both the APK and from the Play Store. Autocomplete for the same page works on Firefox.

![Screenshot_20231024-165849.png](https://github.com/Mosc/Glider/assets/1743850/a0a34cde-fd00-4d58-bf21-a1f9d06d5829)

![Screenshot_20231024-165856.png](https://github.com/Mosc/Glider/assets/1743850/fedc5807-cef0-4a04-ba1a-c44bf30300aa)

**Comment by SuperSandro2000** [comment]
I cannot even access the long press menu to access the paste option.

**Comment by ldavison** [comment]
As a workaround to not being able to long press to paste, type some random letters then double tap on them. This will show the menu where you can "select all" or "paste".

**Comment by Mosc** [comment]
I'm aware that this is a very annoying issue so I've tried to see if migrating from [flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview) to [webview_flutter](https://pub.dev/packages/webview_flutter) would resolve anything, but no dice.

One workaround for Bitwarden specifically is to go to its auto-fill settings and enable "use accessibility", which does allow Bitwarden to overlay a popup.

**Comment by mimi89999** [comment]
Why can't a login view be used?

**Comment by Mosc** [comment]
You mean, like a login page within the app rather than a webview? That caused issues before because the web page will sometimes present us with a captcha, which we can't handle otherwise. Related: #63.

**Comment by Mosc** [comment]
This has been fixed in ff105071a5f26a0fb4ee724e6017a2a33655a173. For whatever reason, the way in app webviews are rendered in Flutter interferes with the way autofill detects fields. Glider now renders the web page as a _native_ webview, full screen, not as part of a Flutter page.

Do speak up if the issue has not been fixed for you as of v2.4.0.
